In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import random
import common.data_utils as data_utils
from itertools import chain

Using TensorFlow backend.


In [5]:
data = data_utils.load_file('data/deeplog/normal_train.txt', to_read=2000, split_token='')[20:22]
max_len, _ = data_utils.dataset_longest_seq(data)
max_len

25

In [3]:
data

[array(['5', '5', '5', '22', '11', '9', '11', '9', '26', '26', '11', '9',
        '26', '23', '23', '23', '21', '21', '21'], dtype='<U2'),
 array(['5', '5', '5', '22', '11', '9', '11', '9', '11', '9', '26', '26',
        '26', '3', '3', '4', '3', '3', '4', '23', '23', '23', '21', '21',
        '21'], dtype='<U2')]

In [257]:
def get_windows_from_dataset(data, window_size, padding):
    sequences = get_dataset_prefixes(data)
    max_len, _ = data_utils.dataset_longest_seq(data)
    return data_utils.pad_dataset(sequences, window_size, padding)
     
def get_seq_prefixes(seq):
    return [seq[:i+1] for i in range(0, len(seq))]

def get_dataset_prefixes(sequences):
    return list(chain.from_iterable([get_seq_prefixes(seq) for seq in sequences]))

def shift_windows(data):
    return data[:len(data)-1], data[1:len(data)]   

In [271]:
data  = [1, 2, 3, 4, 5]
a = get_seq_prefixes(data)
display(data)
display(a)

[1, 2, 3, 4, 5]

[[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]

In [268]:
data  = [[1, 2, 3, 4, 5],[1, 2, 3, 4, 5, 6]]
a = get_dataset_prefixes(data)
display(data)
display(a)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6]]

[[1],
 [1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1],
 [1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5, 6]]

In [282]:
data  = [[1, 2, 3, 4, 5],[1, 2, 3, 4, 5, 6]]
a = get_windows_from_dataset(data, 4, 'pre')
display(data)
display(a)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6]]

[array([0, 0, 0, 1]),
 array([0, 0, 1, 2]),
 array([0, 1, 2, 3]),
 array([1, 2, 3, 4]),
 array([2, 3, 4, 5]),
 array([0, 0, 0, 1]),
 array([0, 0, 1, 2]),
 array([0, 1, 2, 3]),
 array([1, 2, 3, 4]),
 array([2, 3, 4, 5]),
 array([3, 4, 5, 6])]

In [347]:
data = get_windows_from_dataset([[1, 2, 3]], 4, 'pre')
#data: => [[0, 0, 0, 1], [0, 0, 1, 2], [0, 1, 2, 3]]
data = [[1, 2, 3], [4, 5, 6, 7, 8]]
X, Y = shift_windows(data)
display(X)
display(Y)

[[1, 2, 3]]

[[4, 5, 6, 7, 8]]

In [304]:
data  = [[1, 2, 3]]
a = get_windows_from_dataset(data, 4, 'pre')
display(data)
display(a)

[[1, 2, 3]]

[array([0, 0, 0, 1]), array([0, 0, 1, 2]), array([0, 1, 2, 3])]

In [239]:
data_utils.pad_dataset(d, max_len,  padding='pre')

[array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 22]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        22,  5]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,
         5,  5]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,
         5,  5]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,
         5, 26]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,  5,
        26, 11]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,  5, 26,
        11,  9]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,  5, 26, 11,
         9, 26]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,  5, 26, 11,  9,
        26, 26]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,  5, 26, 11,  9, 26,
        26, 11]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0, 22,  5,  5,  5, 26, 